"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Exec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    msg: typing.Text = ...
    def __init__(self,
        *,
        name : typing.Text = ...,
        msg : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"msg",b"msg",u"name",b"name"]) -> None: ...
global___Exec = Exec
