# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_example_common/protos/common/exce.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,grpc_example_common/protos/common/exce.proto\x12\x04\x65xec\x1a\x1bgoogle/protobuf/empty.proto\"!\n\x04\x45xec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\tb\x06proto3')



_EXEC = DESCRIPTOR.message_types_by_name['Exec']
Exec = _reflection.GeneratedProtocolMessageType('Exec', (_message.Message,), {
  'DESCRIPTOR' : _EXEC,
  '__module__' : 'grpc_example_common.protos.common.exce_pb2'
  # @@protoc_insertion_point(class_scope:exec.Exec)
  })
_sym_db.RegisterMessage(Exec)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXEC._serialized_start=83
  _EXEC._serialized_end=116
# @@protoc_insertion_point(module_scope)
